import { ProductWhereUniqueInput } from "../product/ProductWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { SupplierWhereUniqueInput } from "../supplier/SupplierWhereUniqueInput";
import { TransporterWhereUniqueInput } from "../transporter/TransporterWhereUniqueInput";

export type SupplyCreateInput = {
  customerAdvance?: number | null;
  advanceSum?: number | null;
  documentSentDate?: Date | null;
  customerPaymentStatus?: "Option1" | null;
  customerPaymentSum?: number | null;
  gUstatus?: "Option1" | null;
  estimatedCnyRate?: number | null;
  exportContractNumber?: string | null;
  supplyOwner?: string | null;
  actuallyShippedVolume?: number | null;
  plannedTrainDispatch?: Date | null;
  actualTrainDispatch?: Date | null;
  comments?: string | null;
  finish?: boolean | null;
  fss?: string | null;
  st1?: string | null;
  survey?: string | null;
  paymentIssues?: string | null;
  estimatedLogisticsRate?: number | null;
  manager?: string | null;
  deliveryNumber?: string | null;
  secured?: boolean | null;
  status?: "Option1" | null;
  salesVolume?: number | null;
  salesPrice?: number | null;
  sum?: number | null;
  basis?: string | null;
  purchaseRegion?: string | null;
  purchaseVolume?: number | null;
  deficit?: number | null;
  weightedAvgPurchasePrice?: number | null;
  transportRate?: number | null;
  dispatchStartDate?: Date | null;
  trainContractDispatch?: Date | null;
  shipDispatch?: Date | null;
  hedgeStatus?: "Option1" | null;
  paidToSupplier?: number | null;
  supplierPaymentStatus?: "Option1" | null;
  invoiceDirectionDate?: Date | null;
  product?: ProductWhereUniqueInput | null;
  customer?: CustomerWhereUniqueInput | null;
  supplier?: SupplierWhereUniqueInput | null;
  transporter?: TransporterWhereUniqueInput | null;
};
