import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { ProductWhereUniqueInput } from "../product/ProductWhereUniqueInput";
import { CustomerWhereUniqueInput } from "../customer/CustomerWhereUniqueInput";
import { SupplierWhereUniqueInput } from "../supplier/SupplierWhereUniqueInput";
import { TransporterWhereUniqueInput } from "../transporter/TransporterWhereUniqueInput";

export type SupplyWhereInput = {
  id?: StringFilter;
  customerAdvance?: FloatNullableFilter;
  advanceSum?: FloatNullableFilter;
  documentSentDate?: DateTimeNullableFilter;
  customerPaymentStatus?: "Option1";
  customerPaymentSum?: FloatNullableFilter;
  gUstatus?: "Option1";
  estimatedCnyRate?: FloatNullableFilter;
  exportContractNumber?: StringNullableFilter;
  supplyOwner?: StringNullableFilter;
  actuallyShippedVolume?: FloatNullableFilter;
  plannedTrainDispatch?: DateTimeNullableFilter;
  actualTrainDispatch?: DateTimeNullableFilter;
  comments?: StringNullableFilter;
  finish?: BooleanNullableFilter;
  fss?: StringNullableFilter;
  st1?: StringNullableFilter;
  survey?: StringNullableFilter;
  paymentIssues?: StringNullableFilter;
  estimatedLogisticsRate?: FloatNullableFilter;
  manager?: StringNullableFilter;
  deliveryNumber?: StringNullableFilter;
  secured?: BooleanNullableFilter;
  status?: "Option1";
  salesVolume?: FloatNullableFilter;
  salesPrice?: FloatNullableFilter;
  sum?: FloatNullableFilter;
  basis?: StringNullableFilter;
  purchaseRegion?: StringNullableFilter;
  purchaseVolume?: FloatNullableFilter;
  deficit?: FloatNullableFilter;
  weightedAvgPurchasePrice?: FloatNullableFilter;
  transportRate?: FloatNullableFilter;
  dispatchStartDate?: DateTimeNullableFilter;
  trainContractDispatch?: DateTimeNullableFilter;
  shipDispatch?: DateTimeNullableFilter;
  hedgeStatus?: "Option1";
  paidToSupplier?: FloatNullableFilter;
  supplierPaymentStatus?: "Option1";
  invoiceDirectionDate?: DateTimeNullableFilter;
  product?: ProductWhereUniqueInput;
  customer?: CustomerWhereUniqueInput;
  supplier?: SupplierWhereUniqueInput;
  transporter?: TransporterWhereUniqueInput;
};
