/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TransporterService } from "../transporter.service";
import { TransporterCreateInput } from "./TransporterCreateInput";
import { Transporter } from "./Transporter";
import { TransporterFindManyArgs } from "./TransporterFindManyArgs";
import { TransporterWhereUniqueInput } from "./TransporterWhereUniqueInput";
import { TransporterUpdateInput } from "./TransporterUpdateInput";
import { SupplyFindManyArgs } from "../../supply/base/SupplyFindManyArgs";
import { Supply } from "../../supply/base/Supply";
import { SupplyWhereUniqueInput } from "../../supply/base/SupplyWhereUniqueInput";

export class TransporterControllerBase {
  constructor(protected readonly service: TransporterService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Transporter })
  async createTransporter(
    @common.Body() data: TransporterCreateInput
  ): Promise<Transporter> {
    return await this.service.createTransporter({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Transporter] })
  @ApiNestedQuery(TransporterFindManyArgs)
  async transporters(@common.Req() request: Request): Promise<Transporter[]> {
    const args = plainToClass(TransporterFindManyArgs, request.query);
    return this.service.transporters({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Transporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async transporter(
    @common.Param() params: TransporterWhereUniqueInput
  ): Promise<Transporter | null> {
    const result = await this.service.transporter({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Transporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTransporter(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() data: TransporterUpdateInput
  ): Promise<Transporter | null> {
    try {
      return await this.service.updateTransporter({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Transporter })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTransporter(
    @common.Param() params: TransporterWhereUniqueInput
  ): Promise<Transporter | null> {
    try {
      return await this.service.deleteTransporter({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/supplies")
  @ApiNestedQuery(SupplyFindManyArgs)
  async findSupplies(
    @common.Req() request: Request,
    @common.Param() params: TransporterWhereUniqueInput
  ): Promise<Supply[]> {
    const query = plainToClass(SupplyFindManyArgs, request.query);
    const results = await this.service.findSupplies(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        customerAdvance: true,
        advanceSum: true,
        documentSentDate: true,
        customerPaymentStatus: true,
        customerPaymentSum: true,
        gUstatus: true,
        estimatedCnyRate: true,
        exportContractNumber: true,
        supplyOwner: true,
        actuallyShippedVolume: true,
        plannedTrainDispatch: true,
        actualTrainDispatch: true,
        comments: true,
        finish: true,
        fss: true,
        st1: true,
        survey: true,
        paymentIssues: true,
        estimatedLogisticsRate: true,
        manager: true,
        deliveryNumber: true,
        secured: true,
        status: true,
        salesVolume: true,
        salesPrice: true,
        sum: true,
        basis: true,
        purchaseRegion: true,
        purchaseVolume: true,
        deficit: true,
        weightedAvgPurchasePrice: true,
        transportRate: true,
        dispatchStartDate: true,
        trainContractDispatch: true,
        shipDispatch: true,
        hedgeStatus: true,
        paidToSupplier: true,
        supplierPaymentStatus: true,
        invoiceDirectionDate: true,

        product: {
          select: {
            id: true,
          },
        },

        customer: {
          select: {
            id: true,
          },
        },

        supplier: {
          select: {
            id: true,
          },
        },

        transporter: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/supplies")
  async connectSupplies(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() body: SupplyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplies: {
        connect: body,
      },
    };
    await this.service.updateTransporter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/supplies")
  async updateSupplies(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() body: SupplyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplies: {
        set: body,
      },
    };
    await this.service.updateTransporter({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/supplies")
  async disconnectSupplies(
    @common.Param() params: TransporterWhereUniqueInput,
    @common.Body() body: SupplyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplies: {
        disconnect: body,
      },
    };
    await this.service.updateTransporter({
      where: params,
      data,
      select: { id: true },
    });
  }
}
