/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Transporter } from "./Transporter";
import { TransporterCountArgs } from "./TransporterCountArgs";
import { TransporterFindManyArgs } from "./TransporterFindManyArgs";
import { TransporterFindUniqueArgs } from "./TransporterFindUniqueArgs";
import { CreateTransporterArgs } from "./CreateTransporterArgs";
import { UpdateTransporterArgs } from "./UpdateTransporterArgs";
import { DeleteTransporterArgs } from "./DeleteTransporterArgs";
import { SupplyFindManyArgs } from "../../supply/base/SupplyFindManyArgs";
import { Supply } from "../../supply/base/Supply";
import { TransporterService } from "../transporter.service";
@graphql.Resolver(() => Transporter)
export class TransporterResolverBase {
  constructor(protected readonly service: TransporterService) {}

  async _transportersMeta(
    @graphql.Args() args: TransporterCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Transporter])
  async transporters(
    @graphql.Args() args: TransporterFindManyArgs
  ): Promise<Transporter[]> {
    return this.service.transporters(args);
  }

  @graphql.Query(() => Transporter, { nullable: true })
  async transporter(
    @graphql.Args() args: TransporterFindUniqueArgs
  ): Promise<Transporter | null> {
    const result = await this.service.transporter(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Transporter)
  async createTransporter(
    @graphql.Args() args: CreateTransporterArgs
  ): Promise<Transporter> {
    return await this.service.createTransporter({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Transporter)
  async updateTransporter(
    @graphql.Args() args: UpdateTransporterArgs
  ): Promise<Transporter | null> {
    try {
      return await this.service.updateTransporter({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Transporter)
  async deleteTransporter(
    @graphql.Args() args: DeleteTransporterArgs
  ): Promise<Transporter | null> {
    try {
      return await this.service.deleteTransporter(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Supply], { name: "supplies" })
  async findSupplies(
    @graphql.Parent() parent: Transporter,
    @graphql.Args() args: SupplyFindManyArgs
  ): Promise<Supply[]> {
    const results = await this.service.findSupplies(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
