/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SupplierService } from "../supplier.service";
import { SupplierCreateInput } from "./SupplierCreateInput";
import { Supplier } from "./Supplier";
import { SupplierFindManyArgs } from "./SupplierFindManyArgs";
import { SupplierWhereUniqueInput } from "./SupplierWhereUniqueInput";
import { SupplierUpdateInput } from "./SupplierUpdateInput";
import { SupplyFindManyArgs } from "../../supply/base/SupplyFindManyArgs";
import { Supply } from "../../supply/base/Supply";
import { SupplyWhereUniqueInput } from "../../supply/base/SupplyWhereUniqueInput";

export class SupplierControllerBase {
  constructor(protected readonly service: SupplierService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Supplier })
  async createSupplier(
    @common.Body() data: SupplierCreateInput
  ): Promise<Supplier> {
    return await this.service.createSupplier({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Supplier] })
  @ApiNestedQuery(SupplierFindManyArgs)
  async suppliers(@common.Req() request: Request): Promise<Supplier[]> {
    const args = plainToClass(SupplierFindManyArgs, request.query);
    return this.service.suppliers({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Supplier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async supplier(
    @common.Param() params: SupplierWhereUniqueInput
  ): Promise<Supplier | null> {
    const result = await this.service.supplier({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Supplier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSupplier(
    @common.Param() params: SupplierWhereUniqueInput,
    @common.Body() data: SupplierUpdateInput
  ): Promise<Supplier | null> {
    try {
      return await this.service.updateSupplier({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Supplier })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSupplier(
    @common.Param() params: SupplierWhereUniqueInput
  ): Promise<Supplier | null> {
    try {
      return await this.service.deleteSupplier({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/supplies")
  @ApiNestedQuery(SupplyFindManyArgs)
  async findSupplies(
    @common.Req() request: Request,
    @common.Param() params: SupplierWhereUniqueInput
  ): Promise<Supply[]> {
    const query = plainToClass(SupplyFindManyArgs, request.query);
    const results = await this.service.findSupplies(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        customerAdvance: true,
        advanceSum: true,
        documentSentDate: true,
        customerPaymentStatus: true,
        customerPaymentSum: true,
        gUstatus: true,
        estimatedCnyRate: true,
        exportContractNumber: true,
        supplyOwner: true,
        actuallyShippedVolume: true,
        plannedTrainDispatch: true,
        actualTrainDispatch: true,
        comments: true,
        finish: true,
        fss: true,
        st1: true,
        survey: true,
        paymentIssues: true,
        estimatedLogisticsRate: true,
        manager: true,
        deliveryNumber: true,
        secured: true,
        status: true,
        salesVolume: true,
        salesPrice: true,
        sum: true,
        basis: true,
        purchaseRegion: true,
        purchaseVolume: true,
        deficit: true,
        weightedAvgPurchasePrice: true,
        transportRate: true,
        dispatchStartDate: true,
        trainContractDispatch: true,
        shipDispatch: true,
        hedgeStatus: true,
        paidToSupplier: true,
        supplierPaymentStatus: true,
        invoiceDirectionDate: true,

        product: {
          select: {
            id: true,
          },
        },

        customer: {
          select: {
            id: true,
          },
        },

        supplier: {
          select: {
            id: true,
          },
        },

        transporter: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/supplies")
  async connectSupplies(
    @common.Param() params: SupplierWhereUniqueInput,
    @common.Body() body: SupplyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplies: {
        connect: body,
      },
    };
    await this.service.updateSupplier({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/supplies")
  async updateSupplies(
    @common.Param() params: SupplierWhereUniqueInput,
    @common.Body() body: SupplyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplies: {
        set: body,
      },
    };
    await this.service.updateSupplier({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/supplies")
  async disconnectSupplies(
    @common.Param() params: SupplierWhereUniqueInput,
    @common.Body() body: SupplyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      supplies: {
        disconnect: body,
      },
    };
    await this.service.updateSupplier({
      where: params,
      data,
      select: { id: true },
    });
  }
}
